let colorbit_51bit = colorbit.initColorBit(DigitalPin.P1, BitColorMode.RGB)
colorbit_51bit.clear()
colorbit_51bit.showScrollStringColor("Hello!...I am a ColorBit", colorbit.colors(BitColors.Orange))
colorbit_51bit.setBrightness(32)
colorbit_51bit.clear()
colorbit_51bit.setMultiColor(true)
colorbit_51bit.showStringColor("ColorBit", colorbit.colors(BitColors.White))
colorbit_51bit.setMultiColor(false)
basic.forever(function () {
    colorbit_51bit.setBrightness(24)
    basic.pause(100)
    colorbit_51bit.setMultiColor(true)
    colorbit_51bit.showColorIcon(ColorIcon.Heart, colorbit.colors(BitColors.Black))
    colorbit_51bit.setMultiColor(false)
    basic.pause(200)
})
