let colorbit_51bit = colorbit.initColorBit(DigitalPin.P1, BitColorMode.RGB)
colorbit_51bit.clear()
colorbit_51bit.showScrollStringColor("Hello There ...I am a ColorBit", colorbit.colors(BitColors.Red))
colorbit_51bit.setBrightness(32)
colorbit_51bit.clear()
colorbit_51bit.setMultiColor(true)
colorbit_51bit.showStringColor("ColorBit", colorbit.colors(BitColors.Green))
colorbit_51bit.setMultiColor(false)
basic.forever(function () {
    colorbit_51bit.setMultiColor(true)
    colorbit_51bit.showColorIcon(ColorIcon.Ghost, colorbit.colors(BitColors.Black))
    colorbit_51bit.setMultiColor(false)
})
